// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/imansohibul/otp-service/entity"
)

// MockOTPUsecase is a mock of OTPUsecase interface.
type MockOTPUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOTPUsecaseMockRecorder
}

// MockOTPUsecaseMockRecorder is the mock recorder for MockOTPUsecase.
type MockOTPUsecaseMockRecorder struct {
	mock *MockOTPUsecase
}

// NewMockOTPUsecase creates a new mock instance.
func NewMockOTPUsecase(ctrl *gomock.Controller) *MockOTPUsecase {
	mock := &MockOTPUsecase{ctrl: ctrl}
	mock.recorder = &MockOTPUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPUsecase) EXPECT() *MockOTPUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOTPUsecase) Create(ctx context.Context, userID string) (*entity.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(*entity.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOTPUsecaseMockRecorder) Create(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOTPUsecase)(nil).Create), ctx, userID)
}

// Validate mocks base method.
func (m *MockOTPUsecase) Validate(ctx context.Context, userID, otpCode string) (*entity.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, userID, otpCode)
	ret0, _ := ret[0].(*entity.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockOTPUsecaseMockRecorder) Validate(ctx, userID, otpCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockOTPUsecase)(nil).Validate), ctx, userID, otpCode)
}
