// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/imansohibul/otp-service/entity"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTransactionManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTransactionManagerMockRecorder) WithTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTransactionManager)(nil).WithTransaction), ctx, fn)
}

// MockOTPRepository is a mock of OTPRepository interface.
type MockOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPRepositoryMockRecorder
}

// MockOTPRepositoryMockRecorder is the mock recorder for MockOTPRepository.
type MockOTPRepositoryMockRecorder struct {
	mock *MockOTPRepository
}

// NewMockOTPRepository creates a new mock instance.
func NewMockOTPRepository(ctrl *gomock.Controller) *MockOTPRepository {
	mock := &MockOTPRepository{ctrl: ctrl}
	mock.recorder = &MockOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPRepository) EXPECT() *MockOTPRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOTPRepository) Create(ctx context.Context, otp *entity.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOTPRepositoryMockRecorder) Create(ctx, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOTPRepository)(nil).Create), ctx, otp)
}

// FindByUserIDAndCode mocks base method.
func (m *MockOTPRepository) FindByUserIDAndCode(ctx context.Context, userID, otpCode string) (*entity.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndCode", ctx, userID, otpCode)
	ret0, _ := ret[0].(*entity.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndCode indicates an expected call of FindByUserIDAndCode.
func (mr *MockOTPRepositoryMockRecorder) FindByUserIDAndCode(ctx, userID, otpCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndCode", reflect.TypeOf((*MockOTPRepository)(nil).FindByUserIDAndCode), ctx, userID, otpCode)
}

// GetLastByUserID mocks base method.
func (m *MockOTPRepository) GetLastByUserID(ctx context.Context, userID string) (*entity.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastByUserID indicates an expected call of GetLastByUserID.
func (mr *MockOTPRepositoryMockRecorder) GetLastByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastByUserID", reflect.TypeOf((*MockOTPRepository)(nil).GetLastByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockOTPRepository) Update(ctx context.Context, otp *entity.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOTPRepositoryMockRecorder) Update(ctx, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOTPRepository)(nil).Update), ctx, otp)
}
